[PROTHEUS]
SourcePath=/totvs/protheus/apo
RPOCustom=/totvs/protheus/apo/custom.rpo
RPOTLPP=/totvs/protheus/apo/tlpp.rpo
RootPath=/totvs/protheus
StartPath=/system/
RpoDb=SQL
RpoLanguage=Multi
RpoVersion=120
LocalFiles=CTREE
StartSysInDB=1
TopMemoMega=50
SpecialKey=PROTHEUS
DBPort=7890
DBAlias=protheus
DBServer=dbaccess
DBDatabase=POSTGRES

[Drivers]
Active=TCP
MultiProtocolPort=1
MultiProtocolPortSecure=0

[TCP]
TYPE=TCPIP
Port=1240

[LicenseClient]
Server=license-server
Port=5555

[General]
app_environment=PROTHEUS
ShowFullLog=0
MaxStringSize=500
MaxQuerySize=31960
PowerSchemeShowUpgradeSuggestion=0
ConsoleFile=/totvs/protheus/log/appserver.log
ConsoleLog=1
AsyncConsoleLog=1
BuildKillUsers=1
ADVPLVERBOSEASERROR=1
ADVPLVERBOSE=1

[WebApp]
Port=1240
LastMainProg=SIGAADV,SIGACFG,MPSDU,SIGAMDI
EnvServer=PROTHEUS
NonStopOnError=1

[WEBAGENT]
VERSION=1.0.22
DisableIncompatibleSO=1
Windows_x64=/totvs/protheus/tec/webagent/web-agent-1.0.22-windows-x64-release.setup.exe
Windows_x86=
Windows_arm64=
Darwin_x64=
Darwin_arm64=/totvs/protheus/tec/webagent/web-agent_1.0.22_mac_x64.dmg
Darwin_universal=/totvs/protheus/tec/webagent/web-agent_1.0.22_mac-universal.dmg
Linux_x64_deb=/totvs/protheus/tec/webagent/web-agent-1.0.22-linux-x64-release.deb
Linux_arm_deb=
Linux_arm64_deb=
Linux_x64_rpm=/totvs/protheus/tec/webagent/web-agent-1.0.22-linux-x64-release.rpm
Linux_arm_rpm=
Linux_arm64_rpm=
Windows_x64_extras=
Windows_x86_extras=
Linux_x64_extras=
Linux_arm64_extras=

[WebMonitor]
Enable=1

[APP_MONITOR]
Enable=1

[TDS]
AllowMonitor=*
AllowApplyPatch=*
AllowEdit=*
EnableDisconnectUser=*
EnableSendMessage=*
EnableBlockNewConnection=*
EnableStopServer=*

[WebApp/webapp]
MPP=
 
[ONSTART]
Jobs=HTTPJOB
Refreshrate=3600

[HTTPV11]
Enable=1
AddressFamily=1
Sockets=HTTPREST
TimeOut=3600

[HTTPREST]
Port=8080
IPsBind=
URIs=HTTPURI
Security=1
MaxQueue=10
;LogRequest=1
;LogResponse=1

[HTTPURI]
URL=/rest
PrepareIn=99
Instances=1,2,1,1
CORSEnable=0
AllowOrigin=*

[HTTPJOB]
MAIN=HTTP_START
ENVIRONMENT=PROTHEUS
                                                                                                                   
 