services:
    db:
        image: docker.io/rodrigomicrosiga/postgres-dev-protheus:16.9
        container_name: postgresql
        user: root
        ports:
            - "5432:5432"
        env_file:
          - .env
        volumes:
            - /usr/ec2-user/dados/volume/postgres/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - protheus
        restart: always
    license:
        image: docker.io/rodrigomicrosiga/license-dev-protheus:3.7.0
        container_name: license-server
        ports:
            - "8020:8020"
        cap_add:
            - sys_rawio
        ulimits:
            core:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
            stack:
                soft: 1048576
                hard: 1048576
        networks:
            - protheus
    dbaccess:
        image: docker.io/rodrigomicrosiga/dbaccess-dev-protheus:24.1.0.6
        container_name: dbaccess
        ports:
            - "7890:7890"
        env_file:
          - .env
        ulimits:
            core:
                soft: -1
                hard: -1
            nofile:
                soft: 65535
                hard: 65535
            stack:
                soft: 1048576
                hard: 1048576
        networks:
            - protheus
        depends_on:
            - db
            - license
    protheus:
        image: docker.io/rodrigomicrosiga/appserver-dev-protheus:24.3.0.5
        container_name: protheus
        ports:
            - "1240:1240"
            - "8080:8080"
            - "32033:32033"
        environment:
            - ENV_DB=POSTGRES
        cap_add:
            - sys_rawio
        ulimits:
            core:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
            stack:
                soft: 1048576
                hard: 1048576
        networks:
            - protheus
        depends_on:
            - dbaccess
networks:
    protheus:
